agents:
  critic_agent:
    model: "deepseek-chat"
  research_agent:
    model: "deepseek-chat"

tools:
  web_search_zhipu:
    api_key: ""
    num_results: 2

models:
  - models: ["deepseek-chat"]
    model_platform: "deepseek"
    platform_api_key: ""
    temperature: 0.7
